#Github workflow for publishing sicprod pages
#
#SPDX-FileCopyrightText: 2022 Birger Schacht
#SPDX-License-Identifier: MIT

# To be able to create PR in this action, we have to activate
# 'Allow Github Actions to create and approve pull requests'

name: "Update models.py from model.xml and create PR"

on:
  repository_dispatch:
    types: convert

permissions: write-all

jobs:
  createpr:
    name: "Update models.py from model.xml and create PR"
    runs-on: ubuntu-22.04
    env:
      BRANCHNAME: models-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
     - name: Install dependencies
       run: |
          sudo apt update
          sudo apt install python3-lxml python3-jinja2 -y
     - name: Checkout xmltodjangomodel
       uses: actions/checkout@v3
       with:
         repository: acdh-oeaw/xmltodjangomodel
         path: xmltodjangomodel
     - name: Checkout sicprod repository
       uses: actions/checkout@v3
       with:
         repository: SiCProD/sicprod-datamodel
         path: sicprod-datamodel
     - name: Checkout ontologies repository
       uses: actions/checkout@v3
       with:
         path: apis-ontologies
     - name: Build models.py
       run: |
         cd xmltodjangomodel
         python3 convert.py ../sicprod-datamodel/model.xml ../apis-ontologies/sicprod/models.py
     - name: Create PR
       run: |
         cd apis-ontologies
         git config user.name github-actions
         git config user.email github-actions@github.com
         git checkout -b ${{ env.BRANCHNAME }}
         git add sicprod/models.py
         git commit -m 'Updated models.py from sicprod-datamodels repository'
         git push -u origin ${{ env.BRANCHNAME }}
         gh pr create --title 'Updated models.py from sicprod-datamodels worflow' --body 'Updated models.py' -d #--head ${{ env.BRANCHNAME }}
       env:
         GH_TOKEN: ${{ github.token }}
